default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.credentials.dig(:development_and_test, :username)%>
  password: <%= Rails.application.credentials.dig(:development_and_test, :password)%>
  host: <%= Rails.application.credentials.dig(:development_and_test, :host)%>

development:
  <<: *default
  database: lemoney_development

test:
  <<: *default
  database: lemoney_test

production:
  <<: *default
  database: lemoney_production
  username: <%= Rails.application.credentials.dig(:production, :username)%>
  password: <%= Rails.application.credentials.dig(:production, :password)%>
  host: <%= Rails.application.credentials.dig(:production, :host)%>
